# Generated by Django 3.2.12 on 2022-03-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AthletesAndResults',
            fields=[
                ('pk_athlete', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sex', models.IntegerField(choices=[(1, 'M'), (2, 'F')])),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('team', models.CharField(max_length=255)),
                ('noc', models.CharField(max_length=255)),
                ('games', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('season', models.IntegerField(choices=[(1, 'Summer'), (2, 'Winter')])),
                ('city', models.CharField(max_length=255)),
                ('sport', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=255)),
                ('medal', models.IntegerField(choices=[(1, 'Gold'), (2, 'Silver'), (3, 'Bronze'), (4, 'NA')])),
            ],
        ),
    ]
