# Generated by Django 3.2.12 on 2022-03-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AthletesAndResults',
            fields=[
                ('pk_athlete', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('team', models.CharField(max_length=255)),
                ('noc', models.CharField(max_length=255)),
                ('games', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('season', models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter')], max_length=6)),
                ('city', models.CharField(max_length=255)),
                ('sport', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=255)),
                ('medal', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('NA', 'NA')], max_length=6)),
            ],
        ),
    ]
