# Generated by Django 3.2.12 on 2022-03-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celerochallenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletesandresults',
            name='fl_deletado',
            field=models.BooleanField(default=False),
        ),
    ]
